{% set name = "types-protobuf" %}
{% set version = "6.30.2.20250516" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: aecd1881770a9bb225ede66872ef7f0da4505edd0b193108edd9892e48d49a41

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - types-futures

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f $SP_DIR/google-stubs/protobuf/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for protobuf
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
