{% set name = "types-protobuf" %}
{% set version = "5.28.0.20240924" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-protobuf-{{ version }}.tar.gz
  sha256: d181af8a256e5a91ce8d5adb53496e880efd9144c7d54483e3653332b60296f0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - types-futures

test:
  commands:
    - test -f $SP_DIR/google-stubs/protobuf/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for protobuf
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
